- name: ACI Playbook
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:
  - name: Add a new user tenant in apic
    aci_tenant:
      hostname: '{{apic_host}}'
      username: '{{apic_username}}'
      password: '{{apic_password}}'
      use_proxy: '{{apic_use_proxy}}'
      validate_certs: '{{apic_validate_certs}}'
      tenant: ahendraw-TN2
      description: Tenant configured from Ansible
    delegate_to: localhost
 
